project_id = "hgqyyummtpvawdyerqnc"

[functions.send-notification]
verify_jwt = true

[functions.create-intern-user]
verify_jwt = false

[functions.reset-intern-password]
verify_jwt = false

[functions.complete-intern-password-change]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = false

[functions.complete-employee-password-change]
verify_jwt = false

